package com.zld.pay.mapper;

import com.zld.weixin.model.CardInfo;
import com.zld.weixin.model.CardInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CardInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardinfo
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    long countByExample(CardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardinfo
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    int deleteByExample(CardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardinfo
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    int insert(CardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardinfo
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    int insertSelective(CardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardinfo
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    List<CardInfo> selectByExample(CardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardinfo
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") CardInfo record, @Param("example") CardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardinfo
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    int updateByExample(@Param("record") CardInfo record, @Param("example") CardInfoExample example);
}