package com.zld.weixin.model;

public class CardInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardinfo.id
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardinfo.name
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardinfo.phone
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardinfo.company
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardinfo.mail
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardinfo.pos
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    private String pos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardinfo.info
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardinfo.zan
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    private String zan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardinfo.watch
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    private String watch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardinfo.collection
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    private String collection;

    public CardInfo() {
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardinfo.imgurl
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    private String imgurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardinfo.id
     *
     * @return the value of cardinfo.id
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardinfo.id
     *
     * @param id the value for cardinfo.id
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardinfo.name
     *
     * @return the value of cardinfo.name
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    public String getName() {
        return name;
    }

    @Override
    public String toString() {
        return "CardInfo{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", phone='" + phone + '\'' +
                ", company='" + company + '\'' +
                ", mail='" + mail + '\'' +
                ", pos='" + pos + '\'' +
                ", info='" + info + '\'' +
                ", zan='" + zan + '\'' +
                ", watch='" + watch + '\'' +
                ", collection='" + collection + '\'' +
                ", imgurl='" + imgurl + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardinfo.name
     *
     * @param name the value for cardinfo.name
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardinfo.phone
     *
     * @return the value of cardinfo.phone
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardinfo.phone
     *
     * @param phone the value for cardinfo.phone
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardinfo.company
     *
     * @return the value of cardinfo.company
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardinfo.company
     *
     * @param company the value for cardinfo.company
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardinfo.mail
     *
     * @return the value of cardinfo.mail
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardinfo.mail
     *
     * @param mail the value for cardinfo.mail
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardinfo.pos
     *
     * @return the value of cardinfo.pos
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    public String getPos() {
        return pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardinfo.pos
     *
     * @param pos the value for cardinfo.pos
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    public void setPos(String pos) {
        this.pos = pos == null ? null : pos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardinfo.info
     *
     * @return the value of cardinfo.info
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardinfo.info
     *
     * @param info the value for cardinfo.info
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardinfo.zan
     *
     * @return the value of cardinfo.zan
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    public String getZan() {
        return zan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardinfo.zan
     *
     * @param zan the value for cardinfo.zan
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    public void setZan(String zan) {
        this.zan = zan == null ? null : zan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardinfo.watch
     *
     * @return the value of cardinfo.watch
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    public String getWatch() {
        return watch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardinfo.watch
     *
     * @param watch the value for cardinfo.watch
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    public void setWatch(String watch) {
        this.watch = watch == null ? null : watch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardinfo.collection
     *
     * @return the value of cardinfo.collection
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    public String getCollection() {
        return collection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardinfo.collection
     *
     * @param collection the value for cardinfo.collection
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    public void setCollection(String collection) {
        this.collection = collection == null ? null : collection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardinfo.imgurl
     *
     * @return the value of cardinfo.imgurl
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardinfo.imgurl
     *
     * @param imgurl the value for cardinfo.imgurl
     *
     * @mbg.generated Thu Dec 28 16:16:58 CST 2017
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }
}